In [25]:
import pandas as pd

# CSV 파일을 읽어서 DataFrame으로 변환
df = pd.read_csv('master_info.csv')

# 데이터의 상위 5개 행을 출력해서 잘 불러와졌는지 확인
df.head()

,Seq,Title,ShopName,Address,Area (평형),Cost,Style,Space,Apt Name,View Count,Editor,TagList
0,10000,배곧 한라비발디캠퍼스 1단지 50py 인테리어,한샘 한샘리하우스 대리점,경기도 시흥시,50.0,7천만원 이상,모던,"전체,거실,침실,아이방,키친,서재/멀티룸,욕실",한라비발디캠퍼스,400,한샘리하우스 한샘대리점,NaN
1,10002,모던함과 클래식이 공존하는 송도자이하버뷰2단지 47평 C타입,한샘 한샘리하우스 대리점,인천광역시 연수구,47.0,7천만원 이상,모던,"전체,거실,침실,키친,드레스룸,욕실",송도자이하버뷰2단지아파트,231,한샘리하우스 한샘대리점,NaN
2,10003,배곧 한라비발디2차 47평형(156) 모던타입 전체 리모델링,한샘 한샘리하우스 대리점,경기도 시흥시,47.0,7천만원 이상,모던,"전체,거실,침실,아이방,키친,서재/멀티룸,욕실,현관",한라비발디캠퍼스2차,382,한샘리하우스 한샘대리점,NaN
3,10007,구조 변경 없이 더 넓은 거실 만들기┃부천 진달래[49py],디자인밀로 한샘리하우스 대리점,경기도 부천시 원미구,50.0,7천만원 이상,모던,"전체,거실,침실,키친,드레스룸,현관,기타",진달래마을,498,한샘리하우스 디자인밀로대리점,"49평형도면,상동진달래대우,49평형인테리어,49평리모델링,아파트인테리어,진달래대우아..."
4,10011,"하남풍산아이파크 33평, 아치파티션을 이용하여 거실과 주방을 연결!",디자인 로즈 한샘리하우스 대리점,경기도 하남시,33.0,5천만원대,모던,"전체,거실,침실,아이방,키친,욕실,현관",하남풍산아이파크5단지,1111,한샘리하우스 디자인 로즈대리점,"3연동슬라이딩도어,3연동슬라이딩도어,현관인테리어,신발장,행잉형신발장,3연동슬라이딩도..."

In [26]:
df.columns

Index(['Seq', 'Title', 'ShopName', 'Address', 'Area (평형)', 'Cost', 'Style',
       'Space', 'Apt Name', 'View Count', 'Editor', 'TagList'],
      dtype='object')

In [27]:
# 불필요한 열 제거
columns_to_drop = ['ShopName', 'Address', 'Area (평형)', 'Apt Name', 'View Count', 'Editor']
df.drop(columns=columns_to_drop, inplace=True)

In [28]:
df

,Seq,Title,Cost,Style,Space,TagList
0,10000,배곧 한라비발디캠퍼스 1단지 50py 인테리어,7천만원 이상,모던,"전체,거실,침실,아이방,키친,서재/멀티룸,욕실",NaN
1,10002,모던함과 클래식이 공존하는 송도자이하버뷰2단지 47평 C타입,7천만원 이상,모던,"전체,거실,침실,키친,드레스룸,욕실",NaN
2,10003,배곧 한라비발디2차 47평형(156) 모던타입 전체 리모델링,7천만원 이상,모던,"전체,거실,침실,아이방,키친,서재/멀티룸,욕실,현관",NaN
3,10007,구조 변경 없이 더 넓은 거실 만들기┃부천 진달래[49py],7천만원 이상,모던,"전체,거실,침실,키친,드레스룸,현관,기타","49평형도면,상동진달래대우,49평형인테리어,49평리모델링,아파트인테리어,진달래대우아..."
4,10011,"하남풍산아이파크 33평, 아치파티션을 이용하여 거실과 주방을 연결!",5천만원대,모던,"전체,거실,침실,아이방,키친,욕실,현관","3연동슬라이딩도어,3연동슬라이딩도어,현관인테리어,신발장,행잉형신발장,3연동슬라이딩도..."
...,...,...,...,...,...,...
11966,9989,정서발달을 위한 아이방 인테리어,3천만원대,모던,"전체,거실,침실,아이방,키친,다이닝룸,서재/멀티룸,욕실,현관,기타","거실장,슬라이딩거실장,고요한공간,고요한공간,모던클래식욕실,샤워가즐거운,관리하기쉬운,..."
11967,999,1인가구를 위한 한샘 모던화이트 리모델링,1천만원대,모던,키친,NaN
11968,9991,"25평 아파트에 대면형 주방설계, 모던하고 호텔같은 리모델링",6천만원대,모던,"전체,거실,침실,아이방,키친,서재/멀티룸,욕실,현관,기타",NaN
11969,9993,거실 속 고즈넉한 툇마루! 화이트톤의 미니멀 50평대 아파트 리모델링,7천만원 이상,모던,"전체,거실,침실,아이방,키친,서재/멀티룸,욕실,현관,기타","서재인테리어,멀티룸인테리어,아이방인테리어,침실인테리어,자녀방인테리어,욕실인테리어,욕..."
11970,9995,조명을 잘 활용한 화이트 베이스의 웜톤 인테리어,6천만원대,모던,"전체,거실,침실,아이방,키친,드레스룸,욕실,기타",NaN

In [ ]:
import pandas as pd

# 예시 df 로드 (사용자 환경에 맞게 변경)
# df = pd.read_csv('master_info.csv')

# 1. 'Space' 컬럼에서 결측값 제외 후 쉼표 기준으로 분리 + 공백 제거
space_split = df['Space'].dropna().apply(lambda x: [s.strip() for s in x.split(',')])

# 2. 리스트를 평탄화(flatten)
all_spaces = [item for sublist in space_split for item in sublist]

# 3. 중복 제거 및 정렬
unique_spaces = sorted(set(all_spaces))

print("유니크 공간 목록 : ", unique_spaces)

# 4. 코드 부여 (기타는 9999, 나머지는 0000부터 4자리 0패딩)
final_area_codes = {}
code = 0
for name in unique_spaces:
    if name == '기타':
        final_area_codes[name] = '9999'
    else:
        final_area_codes[name] = str(code).zfill(4)
        code += 1

# 5. DataFrame 생성 및 번호 순 정렬
df_area = pd.DataFrame([
    {'area_name': name, 'area_no': final_area_codes[name]} for name in final_area_codes
])
df_area = df_area.sort_values(by='area_no').reset_index(drop=True)

# 6. 출력 및 CSV 저장
print(df_area)
df_area.to_csv('area_category.csv', index=False, encoding='utf-8-sig')

['거실', '기타', '다이닝룸', '드레스룸', '발코니', '서재/멀티룸', '아이방', '욕실', '전체', '침실', '키친', '현관']

In [20]:
import pandas as pd

# 항목 및 커스텀 번호 부여
custom_area_codes = {
    '기타': '9998',
    '전체': '9999'
}

area_names = ['거실', '기타', '다이닝룸', '드레스룸', '발코니', '서재/멀티룸', '아이방', '욕실', '전체', '침실', '키친', '현관']
regular_areas = [area for area in area_names if area not in custom_area_codes]
regular_area_codes = {area: f"{i:04d}" for i, area in enumerate(sorted(regular_areas))}

# 코드 딕셔너리 병합
final_area_codes = {**regular_area_codes, **custom_area_codes}

# DataFrame 생성 후 정렬
df_area = pd.DataFrame([
    {'area_name': name, 'area_no': final_area_codes[name]} for name in final_area_codes
])
df_area = df_area.sort_values(by='area_no').reset_index(drop=True)

# 출력 + 저장
print(df_area)
df_area.to_csv('area_category.csv', index=False)

   area_name area_no
0         거실    0000
1       다이닝룸    0001
2       드레스룸    0002
3        발코니    0003
4     서재/멀티룸    0004
5        아이방    0005
6         욕실    0006
7         침실    0007
8         키친    0008
9         현관    0009
10        기타    9998
11        전체    9999

In [21]:
import pandas as pd

# 비용 카테고리 정의 (만원 단위 기준)
cost_data = [
    {"cost_name": "1천만원 미만",     "cost_code": 1, "cost_min": 0,     "cost_max": 1000},
    {"cost_name": "1천만원대",        "cost_code": 2, "cost_min": 1000,  "cost_max": 2000},
    {"cost_name": "2천만원대",        "cost_code": 3, "cost_min": 2000,  "cost_max": 3000},
    {"cost_name": "3천만원대",        "cost_code": 4, "cost_min": 3000,  "cost_max": 4000},
    {"cost_name": "4천만원대",        "cost_code": 5, "cost_min": 4000,  "cost_max": 5000},
    {"cost_name": "5천만원대",        "cost_code": 6, "cost_min": 5000,  "cost_max": 6000},
    {"cost_name": "6천만원대",        "cost_code": 7, "cost_min": 6000,  "cost_max": 7000},
    {"cost_name": "7천만원 ~ 1억원",  "cost_code": 8, "cost_min": 7000,  "cost_max": 10000},
    {"cost_name": "1억원 이상",       "cost_code": 9, "cost_min": 10000, "cost_max": float('inf')},
]

# DataFrame 생성
df_cost = pd.DataFrame(cost_data)

# 무한대는 csv에 그대로 저장되지 않으므로 문자열 처리 (선택)
df_cost['cost_max'] = df_cost['cost_max'].apply(lambda x: 'inf' if x == float('inf') else x)

# CSV 저장
df_cost.to_csv("cost_category.csv", index=False, encoding='utf-8-sig')  # 한글 포함 시 utf-8-sig 권장

In [24]:
# 1) 'Style' 컬럼의 결측값 처리 (필요하면)
df['Style'] = df['Style'].fillna('기타')

# 2) &amp; → & 변환 + , 기준으로 분리
style_series = df['Style'].str.replace('&amp;', '&', regex=False)

# 3) 각 행을 ',' 기준으로 나누고 리스트로 변환
style_lists = style_series.str.split(',')

# 4) 모든 스타일을 평탄화(flatten)하고 strip으로 공백 제거
all_styles = [style.strip() for sublist in style_lists for style in sublist]

# 5) 유니크한 값 추출 후 정렬
unique_styles = sorted(set(all_styles) - {'기타'})
unique_styles.append('기타')

print("유니크 스타일 목록:", unique_styles)

# 6) 스타일 코드 부여 (0부터 순차적)
style_data = []
for idx, name in enumerate(unique_styles):
    if name == '기타':
        code = '9999'
    else:
        code = str(idx).zfill(4)  # 0부터 시작, 4자리 0패딩
    style_data.append({"style_name": name, "style_code": code})

# 7) DataFrame 생성 및 CSV 저장
df_style = pd.DataFrame(style_data)
df_style.to_csv("style_category.csv", index=False, encoding='utf-8-sig')

유니크 스타일 목록: ['내추럴', '모던', '빈티지&앤틱', '심플&미니멀', '클래식', '한국&동양적', '기타']

In [29]:
df

,Seq,Title,Cost,Style,Space,TagList
0,10000,배곧 한라비발디캠퍼스 1단지 50py 인테리어,7천만원 이상,모던,"전체,거실,침실,아이방,키친,서재/멀티룸,욕실",NaN
1,10002,모던함과 클래식이 공존하는 송도자이하버뷰2단지 47평 C타입,7천만원 이상,모던,"전체,거실,침실,키친,드레스룸,욕실",NaN
2,10003,배곧 한라비발디2차 47평형(156) 모던타입 전체 리모델링,7천만원 이상,모던,"전체,거실,침실,아이방,키친,서재/멀티룸,욕실,현관",NaN
3,10007,구조 변경 없이 더 넓은 거실 만들기┃부천 진달래[49py],7천만원 이상,모던,"전체,거실,침실,키친,드레스룸,현관,기타","49평형도면,상동진달래대우,49평형인테리어,49평리모델링,아파트인테리어,진달래대우아..."
4,10011,"하남풍산아이파크 33평, 아치파티션을 이용하여 거실과 주방을 연결!",5천만원대,모던,"전체,거실,침실,아이방,키친,욕실,현관","3연동슬라이딩도어,3연동슬라이딩도어,현관인테리어,신발장,행잉형신발장,3연동슬라이딩도..."
...,...,...,...,...,...,...
11966,9989,정서발달을 위한 아이방 인테리어,3천만원대,모던,"전체,거실,침실,아이방,키친,다이닝룸,서재/멀티룸,욕실,현관,기타","거실장,슬라이딩거실장,고요한공간,고요한공간,모던클래식욕실,샤워가즐거운,관리하기쉬운,..."
11967,999,1인가구를 위한 한샘 모던화이트 리모델링,1천만원대,모던,키친,NaN
11968,9991,"25평 아파트에 대면형 주방설계, 모던하고 호텔같은 리모델링",6천만원대,모던,"전체,거실,침실,아이방,키친,서재/멀티룸,욕실,현관,기타",NaN
11969,9993,거실 속 고즈넉한 툇마루! 화이트톤의 미니멀 50평대 아파트 리모델링,7천만원 이상,모던,"전체,거실,침실,아이방,키친,서재/멀티룸,욕실,현관,기타","서재인테리어,멀티룸인테리어,아이방인테리어,침실인테리어,자녀방인테리어,욕실인테리어,욕..."
11970,9995,조명을 잘 활용한 화이트 베이스의 웜톤 인테리어,6천만원대,모던,"전체,거실,침실,아이방,키친,드레스룸,욕실,기타",NaN

In [31]:
df['space_count'] = df['Space'].str.count(',') + 1

## 수정

In [36]:
import pandas as pd
import numpy as np

# --- 1단계: 데이터 로드 및 기본 전처리 ---

# CSV 파일을 읽어서 DataFrame으로 변환
# 'master_info.csv' 파일이 없으면 예시 데이터를 생성합니다.
try:
    df = pd.read_csv('master_info.csv')
except FileNotFoundError:
    print("'master_info.csv' 파일을 찾을 수 없어 예시 데이터로 진행합니다.")
    data = {
        'Seq': [10000, 10001, 10002, 10003, 10004],
        'ShopName': ['한샘', '한샘', '까사미아', '이케아', '한샘'],
        'Address': ['서울', '경기', '서울', '광명', '부산'],
        'Area (평형)': [50, 47, 32, 25, 50],
        'Apt Name': ['래미안', '자이', '힐스테이트', '푸르지오', '래미안'],
        'View Count': [400, 231, 500, 120, 330],
        'Editor': ['에디터A', '에디터B', '에디터A', '에디터C', '에디터B'],
        'Space': ['전체,거실,침실', '거실,키친,욕실', '거실,주방', np.nan, '기타'],
        'Cost': ['7천만원 이상', '5천만원', '5천만원', '3천만원', '7천만원 이상'],
        'Style': ['모던', '클래식&amp;모던', '미니멀', '북유럽', np.nan]
    }
    df = pd.DataFrame(data)


# 불필요한 열 제거
columns_to_drop = ['ShopName', 'Address', 'Area (평형)', 'Apt Name', 'View Count', 'Editor']
existing_columns_to_drop = [col for col in columns_to_drop if col in df.columns]
df.drop(columns=existing_columns_to_drop, inplace=True)

print("--- 1. 초기 데이터 로드 및 불필요한 컬럼 제거 완료 ---")
print(df.head())
print("-" * 50)


# --- 2단계: 'Space' 컬럼 분석 및 카테고리 코드 생성/저장 ---

space_split = df['Space'].dropna().apply(lambda x: [s.strip() for s in x.split(',')])
all_spaces = [item for sublist in space_split for item in sublist]
unique_spaces = sorted(list(set(all_spaces)))

final_area_codes = {}
code = 1
for name in unique_spaces:
    if name == '기타':
        final_area_codes[name] = 'spa_9999'
    else:
        final_area_codes[name] = f"spa_{str(code).zfill(4)}"
        code += 1

df_area = pd.DataFrame(list(final_area_codes.items()), columns=['name', 'code'])
df_area = df_area.sort_values(by='code').reset_index(drop=True)
df_area = df_area[['code', 'name']]
df_area.to_csv('area_category.csv', index=False, encoding='utf-8-sig')

print("--- 2. 'Space' 카테고리 코드 생성 및 'area_category.csv' 저장 완료 ---")
print(df_area)
print("-" * 50)


# --- 3단계: 'Cost' 컬럼 분석 및 카테고리 코드 생성/저장 ---

unique_costs = sorted(df['Cost'].dropna().unique())
final_cost_codes = {}
code = 1
for name in unique_costs:
    final_cost_codes[name] = f"cos_{str(code).zfill(4)}"
    code += 1

df_cost = pd.DataFrame(list(final_cost_codes.items()), columns=['name', 'code'])
df_cost = df_cost.sort_values(by='code').reset_index(drop=True)
df_cost = df_cost[['code', 'name']]
df_cost.to_csv('cost_category.csv', index=False, encoding='utf-8-sig')

print("--- 3. 'Cost' 카테고리 코드 생성 및 'cost_category.csv' 저장 완료 ---")
print(df_cost)
print("-" * 50)


# --- 4단계: 'Style' 컬럼 분석 및 카테고리 코드 생성/저장 ---

# 결측값을 '기타'로 채우고 '&amp;'를 '&'로 변환
df['Style'].fillna('기타', inplace=True)
style_series = df['Style'].str.replace('&amp;', '&', regex=False)

# 쉼표로 분리하고 평탄화하여 유니크한 스타일 목록 추출
style_lists = style_series.str.split(',')
all_styles = [style.strip() for sublist in style_lists for style in sublist]
unique_styles = sorted(list(set(all_styles)))

print("--- 4a. 유니크 스타일 목록 추출 완료 ---")
print(unique_styles)
print("-" * 50)

# 'sty_XXXX' 형식으로 스타일 카테고리 코드 생성
final_style_codes = {}
code = 1
for name in unique_styles:
    if name == '기타':
        final_style_codes[name] = 'sty_9999'
    else:
        final_style_codes[name] = f"sty_{str(code).zfill(4)}"
        code += 1

# 생성된 코드 맵을 DataFrame으로 변환하고 컬럼명/순서 변경
df_style = pd.DataFrame(list(final_style_codes.items()), columns=['name', 'code'])
df_style = df_style.sort_values(by='code').reset_index(drop=True)
df_style = df_style[['code', 'name']]
df_style.to_csv('style_category.csv', index=False, encoding='utf-8-sig')

print("--- 4b. 'Style' 카테고리 코드 생성 및 'style_category.csv' 저장 완료 ---")
print(df_style)
print("-" * 50)


# --- 5단계: 원본 DataFrame에 생성된 코드 적용 ---

# 'Space'를 코드로 변환하는 함수
def convert_space_to_codes(space_string):
    if pd.isna(space_string) or not isinstance(space_string, str):
        return space_string
    spaces = [s.strip() for s in space_string.split(',')]
    codes = [final_area_codes.get(s, "CODE_NOT_FOUND") for s in spaces]
    return ','.join(codes)

# 'Style'을 코드로 변환하는 함수
def convert_style_to_codes(style_string):
    if pd.isna(style_string): # 이미 fillna를 했지만 안전장치로 남겨둠
        return 'sty_9999'
    processed_string = style_string.replace('&amp;', '&')
    styles = [s.strip() for s in processed_string.split(',')]
    codes = [final_style_codes.get(s, "CODE_NOT_FOUND") for s in styles]
    return ','.join(codes)

# 각 컬럼에 코드 적용
df['apply_space'] = df['Space'].apply(convert_space_to_codes)
df['apply_cost'] = df['Cost'].map(final_cost_codes)
df['apply_style'] = df['Style'].apply(convert_style_to_codes)

# 원본 'Space', 'Cost', 'Style' 컬럼은 삭제
df.drop(columns=['Space', 'Cost', 'Style'], inplace=True)


print("--- 5. 원본 데이터에 코드 적용 완료 ---")
# 최종 결과 확인 (apply_ 컬럼들이 추가되고 원본 컬럼 삭제됨)
print(df.head())
print("-" * 50)

# (선택) 모든 전처리가 완료된 DataFrame을 새로운 CSV 파일로 저장
df.to_csv('master_info_preprocessed.csv', index=False, encoding='utf-8-sig')
print("'master_info_preprocessed.csv' 파일 저장이 완료되었습니다.")

--- 1. 초기 데이터 로드 및 불필요한 컬럼 제거 완료 ---
     Seq                                  Title     Cost Style  \
0  10000              배곧 한라비발디캠퍼스 1단지 50py 인테리어  7천만원 이상    모던
1  10002      모던함과 클래식이 공존하는 송도자이하버뷰2단지 47평 C타입  7천만원 이상    모던
2  10003      배곧 한라비발디2차 47평형(156) 모던타입 전체 리모델링  7천만원 이상    모던
3  10007      구조 변경 없이 더 넓은 거실 만들기┃부천 진달래[49py]  7천만원 이상    모던
4  10011  하남풍산아이파크 33평, 아치파티션을 이용하여 거실과 주방을 연결!    5천만원대    모던

                          Space  \
0     전체,거실,침실,아이방,키친,서재/멀티룸,욕실
1           전체,거실,침실,키친,드레스룸,욕실
2  전체,거실,침실,아이방,키친,서재/멀티룸,욕실,현관
3        전체,거실,침실,키친,드레스룸,현관,기타
4         전체,거실,침실,아이방,키친,욕실,현관

                                             TagList
0                                                NaN
1                                                NaN
2                                                NaN
3  49평형도면,상동진달래대우,49평형인테리어,49평리모델링,아파트인테리어,진달래대우아...
4  3연동슬라이딩도어,3연동슬라이딩도어,현관인테리어,신발장,행잉형신발장,3연동슬라이딩도...
--------------------------------------------------
--- 2. 'Space' 카테고리 코드 생성 및 'area_category.csv' 저장 완료 ---
        code    name
0   spa_0001      거실
1   spa_0002    다이닝룸
2   spa_0003    드레스룸
3   spa_0004     발코니
4   spa_0005  서재/멀티룸
5   spa_0006     아이방
6   spa_0007      욕실
7   spa_0008      전체
8   spa_0009      침실
9   spa_0010      키친
10  spa_0011      현관
11  spa_9999      기타
--------------------------------------------------
--- 3. 'Cost' 카테고리 코드 생성 및 'cost_category.csv' 저장 완료 ---
       code     name
0  cos_0001   1억원 이상
1  cos_0002  1천만원 미만
2  cos_0003    1천만원대
3  cos_0004    2천만원대
4  cos_0005    3천만원대
5  cos_0006    4천만원대
6  cos_0007    5천만원대
7  cos_0008    6천만원대
8  cos_0009  7천만원 이상
--------------------------------------------------
--- 4a. 유니크 스타일 목록 추출 완료 ---
['기타', '내추럴', '모던', '빈티지&앤틱', '심플&미니멀', '클래식', '한국&동양적']
--------------------------------------------------
--- 4b. 'Style' 카테고리 코드 생성 및 'style_category.csv' 저장 완료 ---
       code    name
0  sty_0001     내추럴
1  sty_0002      모던
2  sty_0003  빈티지&앤틱
3  sty_0004  심플&미니멀
4  sty_0005     클래식
5  sty_0006  한국&동양적
6  sty_9999      기타
--------------------------------------------------
--- 5. 원본 데이터에 코드 적용 완료 ---
     Seq                                  Title  \
0  10000              배곧 한라비발디캠퍼스 1단지 50py 인테리어
1  10002      모던함과 클래식이 공존하는 송도자이하버뷰2단지 47평 C타입
2  10003      배곧 한라비발디2차 47평형(156) 모던타입 전체 리모델링
3  10007      구조 변경 없이 더 넓은 거실 만들기┃부천 진달래[49py]
4  10011  하남풍산아이파크 33평, 아치파티션을 이용하여 거실과 주방을 연결!

                                             TagList  \
0                                                NaN
1                                                NaN
2                                                NaN
3  49평형도면,상동진달래대우,49평형인테리어,49평리모델링,아파트인테리어,진달래대우아...
4  3연동슬라이딩도어,3연동슬라이딩도어,현관인테리어,신발장,행잉형신발장,3연동슬라이딩도...

                                         apply_space apply_cost apply_style
0  spa_0008,spa_0001,spa_0009,spa_0006,spa_0010,s...   cos_0009    sty_0002
1  spa_0008,spa_0001,spa_0009,spa_0010,spa_0003,s...   cos_0009    sty_0002
2  spa_0008,spa_0001,spa_0009,spa_0006,spa_0010,s...   cos_0009    sty_0002
3  spa_0008,spa_0001,spa_0009,spa_0010,spa_0003,s...   cos_0009    sty_0002
4  spa_0008,spa_0001,spa_0009,spa_0006,spa_0010,s...   cos_0007    sty_0002
--------------------------------------------------
'master_info_preprocessed.csv' 파일 저장이 완료되었습니다.

/tmp/ipykernel_8040/3814333273.py:84: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Style'].fillna('기타', inplace=True)

In [3]:
import pandas as pd

df_master = pd.read_csv('master_info_preprocessed.csv')
df_comb = pd.read_csv('text_image_combined.csv')

In [4]:
df_master.isnull().sum()

Seq               0
Title             0
TagList        8494
apply_space      41
apply_cost     5501
apply_style       0
dtype: int64

In [5]:
df_master = df_master.dropna(subset=['apply_cost'])
df_master = df_master.dropna(subset=['apply_space'])

In [6]:
df_master

,Seq,Title,TagList,apply_space,apply_cost,apply_style
0,10000,배곧 한라비발디캠퍼스 1단지 50py 인테리어,NaN,"spa_0008,spa_0001,spa_0009,spa_0006,spa_0010,s...",cos_0009,sty_0002
1,10002,모던함과 클래식이 공존하는 송도자이하버뷰2단지 47평 C타입,NaN,"spa_0008,spa_0001,spa_0009,spa_0010,spa_0003,s...",cos_0009,sty_0002
2,10003,배곧 한라비발디2차 47평형(156) 모던타입 전체 리모델링,NaN,"spa_0008,spa_0001,spa_0009,spa_0006,spa_0010,s...",cos_0009,sty_0002
3,10007,구조 변경 없이 더 넓은 거실 만들기┃부천 진달래[49py],"49평형도면,상동진달래대우,49평형인테리어,49평리모델링,아파트인테리어,진달래대우아...","spa_0008,spa_0001,spa_0009,spa_0010,spa_0003,s...",cos_0009,sty_0002
4,10011,"하남풍산아이파크 33평, 아치파티션을 이용하여 거실과 주방을 연결!","3연동슬라이딩도어,3연동슬라이딩도어,현관인테리어,신발장,행잉형신발장,3연동슬라이딩도...","spa_0008,spa_0001,spa_0009,spa_0006,spa_0010,s...",cos_0007,sty_0002
...,...,...,...,...,...,...
11966,9989,정서발달을 위한 아이방 인테리어,"거실장,슬라이딩거실장,고요한공간,고요한공간,모던클래식욕실,샤워가즐거운,관리하기쉬운,...","spa_0008,spa_0001,spa_0009,spa_0006,spa_0010,s...",cos_0005,sty_0002
11967,999,1인가구를 위한 한샘 모던화이트 리모델링,NaN,spa_0010,cos_0003,sty_0002
11968,9991,"25평 아파트에 대면형 주방설계, 모던하고 호텔같은 리모델링",NaN,"spa_0008,spa_0001,spa_0009,spa_0006,spa_0010,s...",cos_0008,sty_0002
11969,9993,거실 속 고즈넉한 툇마루! 화이트톤의 미니멀 50평대 아파트 리모델링,"서재인테리어,멀티룸인테리어,아이방인테리어,침실인테리어,자녀방인테리어,욕실인테리어,욕...","spa_0008,spa_0001,spa_0009,spa_0006,spa_0010,s...",cos_0009,sty_0002
11970,9995,조명을 잘 활용한 화이트 베이스의 웜톤 인테리어,NaN,"spa_0008,spa_0001,spa_0009,spa_0006,spa_0010,s...",cos_0008,sty_0002

In [43]:
df_comb.columns

Index(['Seq', '텍스트', '이미지'], dtype='object')

In [1]:
import pandas as pd

# --- 설정 ---
# 원본 파일과 결과를 저장할 파일 이름을 지정합니다.
input_file = 'text_image_combined.csv'
output_file = 'text_image_deduplicated.csv'

try:
    # --- 1단계: 원본 CSV 파일 로드 ---
    print(f"'{input_file}' 파일을 로드합니다...")
    df = pd.read_csv(input_file)
    rows_before = len(df)
    print(f"-> 중복 제거 전 전체 행의 수: {rows_before}개")
    print("-" * 50)

    # --- 2단계: 중복 행 제거 ---
    # 'subset'에 지정된 컬럼들의 값이 모두 동일한 행을 중복으로 간주합니다.
    # keep='first' 옵션은 중복된 행들 중 첫 번째 행만 남기고 나머지를 삭제합니다.
    print("'Seq', '텍스트' 기준 중복 행을 제거합니다...")
    df_deduplicated = df.drop_duplicates(subset=['Seq', '텍스트'], keep='first')
    rows_after = len(df_deduplicated)
    print("-> 중복 제거 완료!")
    print("-" * 50)

    # --- 3단계: 결과 저장 및 요약 출력 ---
    # 중복이 제거된 결과를 새로운 CSV 파일로 저장합니다.
    df_deduplicated.to_csv(output_file, index=False, encoding='utf-8-sig')

    print("--- 작업 요약 ---")
    print(f"중복 제거 전: {rows_before}개 행")
    print(f"중복 제거 후: {rows_after}개 행")
    print(f"삭제된 중복 행: {rows_before - rows_after}개 행")
    print(f"\n결과가 '{output_file}' 파일로 성공적으로 저장되었습니다.")

except FileNotFoundError:
    print(f"오류: '{input_file}' 파일을 찾을 수 없습니다. 파일이 스크립트와 같은 위치에 있는지 확인해주세요.")
except KeyError as e:
    print(f"오류: {e} 컬럼을 찾을 수 없습니다. '{input_file}' 파일의 컬럼명을 확인해주세요. (예: 'Seq', '텍스트', '이미지')")
except Exception as e:
    print(f"알 수 없는 오류가 발생했습니다: {e}")

'text_image_combined.csv' 파일을 로드합니다...
-> 중복 제거 전 전체 행의 수: 231697개
--------------------------------------------------
'Seq', '텍스트' 기준 중복 행을 제거합니다...
-> 중복 제거 완료!
--------------------------------------------------
--- 작업 요약 ---
중복 제거 전: 231697개 행
중복 제거 후: 98044개 행
삭제된 중복 행: 133653개 행

결과가 'text_image_deduplicated.csv' 파일로 성공적으로 저장되었습니다.

In [7]:
# 1. df_master의 'Seq' 값을 리스트(또는 Series)로 가져옵니다.
master_seq_list2 = df_master['Seq'].tolist()

# 2. isin()을 사용해 df_combined의 'Seq' 값이 master_seq_list에 포함되는지 확인합니다.
#    포함되는 행만 True로 구성된 boolean Series가 생성됩니다.
is_in_master2 = df_deduplicated['Seq'].isin(master_seq_list2)

# 3. boolean Series를 사용해 df_combined 데이터프레임에서 True인 행만 필터링합니다.
df_filtered3 = df_deduplicated[is_in_master2]

print("row 개수 : ", len(df_filtered3))

row 개수 :  38645

In [8]:
df_filtered3

,Seq,텍스트,이미지
0,10000,배곧 한라비발디 캠퍼스 1단지 50평형 인테리어를 소개합니다 거실확장형으로 따뜻하고...,https://image.hanssem.com/hsimg/upload/homeIde...
1,10000,거실시점 주방뷰입니다,https://image.hanssem.com/hsimg/upload/homeIde...
3,10000,한샘 제타화이트 제품으로 깔끔한느낌과 주방입구쪽 파티션시공하여 ㄷ자주방 시공. 수납...,https://image.hanssem.com/hsimg/upload/homeIde...
4,10000,베이지톤 따듯한느낌의 600*600각 타일시공하였습니다.,https://image.hanssem.com/hsimg/upload/homeIde...
5,10000,"안방욕실입니다. 600*600각 라이트그레이 타일시공 넓어보이는효과, 욕조에이프런 ...",https://image.hanssem.com/hsimg/upload/homeIde...
...,...,...,...
231690,9995,"주방 key1 - 화이트 베이스의 주방 컬러와, 식탁 및 냉장고의 포인트 컬러가 만...",https://image.hanssem.com/hsimg/upload/homeIde...
231692,9995,드레스룸 key1 - 한샘 바흐 시스템장으로 답답하지 않은 드레스룸 완성 key2 ...,https://image.hanssem.com/hsimg/upload/homeIde...
231693,9995,자녀방 key1 - 수납력이 높으 책상과 붙박이장을 설치해 독립된 공간을 제공,https://image.hanssem.com/hsimg/upload/homeIde...
231694,9995,"안방 key1 - 붙박이장과 화장대, 부부욕실로 독립된 부부 공간",https://image.hanssem.com/hsimg/upload/homeIde...
231695,9995,"욕실 key1 - 한샘 휴판넬, 휴플로어로 편하게 욕실을 관리하자! key2 - 플...",https://image.hanssem.com/hsimg/upload/homeIde...

In [9]:
import pandas as pd

# 삭제 조건 1: 완전 일치하는 문자열 목록
exact_matches = ['▼▼▼', '-', '[공사 중 사진]', '- epilogue -', '# 현장 설명 #', '.']

# 삭제 조건 2: 포함되는 문자열 목록
contains_keywords = [
    '도면', 'before', 'Before', 'BEFORE', '시공 전', '공사 전', '철거', '공사전', '시공전', '안녕', '시 공 전', 
    '이전', '중간', '평면도', '세월의 흔적', 'Bofore', 'plan', '일정표', 'Plan', 'PLAN', '전',
    '준비 중', '작업 중', '진행 중', '시작 전', '완료 전', '진행 상황', '중간 단계',
    '철거 전', '철거 완료', '기초 공사', '해체', '기초', '배관', '배선', '시공 과정', '시공 과정 사진',
    '현장 사진', '작업 사진', '진행 사진', '현장 상황', '현장 기록', '공사 기록',
    '설계도', '플랜', '계획서', '프로젝트 계획', '스케치',
    '전후', '비포', '애프터', 'before & after', 'before-after', '초기', '시작', '시공 전후', '철거 중',
    '요약', '렌더링', 'Rendering', 'rendering', 'after', 'After', 'A안', 'B안',
    '현장 소개', '현장소개', '공사 후', '공사후', 'INTRO', 'Intro', 'intro', '3D'
]

# 조건 1: 완전 일치
cond_exact = df_filtered3['텍스트'].isin(exact_matches)

# 조건 2: 키워드 포함
cond_contains = df_filtered3['텍스트'].str.contains('|'.join(contains_keywords), case=False, na=False)

# 조건 3: 띄어쓰기 없는 텍스트
cond_no_space = df_filtered3['텍스트'].str.strip().str.contains(r'^\S+$', na=False)

# 조건 4: 특수문자로만 구성된 텍스트
cond_special_chars_only = df_filtered3['텍스트'].str.strip().str.match(r'^[^A-Za-z0-9가-힣]+$', na=False)

# ✅ 조건 5: 텍스트가 10글자 이하
cond_short_length = df_filtered3['텍스트'].str.strip().str.len() <= 30

# 조건 11: 텍스트가 큰따옴표로만 감싸진 경우 (ASCII 큰따옴표 " 또는 한글 큰따옴표 “ ”)
cond_quoted_text = df_filtered3['텍스트'].str.strip().str.match(r'^(["“”]).*\1$', na=False)

# 최종 조건 통합
final_condition = (
    cond_exact |
    cond_contains |
    cond_no_space |
    cond_special_chars_only |
    cond_short_length | 
    cond_quoted_text
)

# 삭제할 행 개수 확인
print(f"삭제 대상 행 개수: {final_condition.sum()}")

삭제 대상 행 개수: 23447

In [10]:
# 조건에 해당하는 행 삭제
df_filtered3 = df_filtered3[~final_condition]

In [11]:
df_filtered3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15198 entries, 0 to 231695
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Seq     15198 non-null  int64
 1   텍스트     15198 non-null  object
 2   이미지     15198 non-null  object
dtypes: int64(1), object(2)
memory usage: 474.9+ KB

In [12]:
df_filtered3.to_csv("시공사례이미지2.csv", index=False, encoding='utf-8-sig')

In [16]:
import pandas as pd

df111 = pd.read_csv("master_info_preprocessed.csv")

# 1. TagList에서 빈값이 아닌 row만 필터링
valid_seq_list = df111[df111['TagList'].apply(lambda x: not(pd.isna(x) or str(x).strip() == ''))]['Seq']

# 2. df_filtered3에서 Seq가 위의 Seq 목록에 포함되는 row만 필터링
matched_rows = df_filtered3[df_filtered3['Seq'].isin(valid_seq_list)]

# 3. 개수 출력
print(f"조건에 해당하는 valid_seq_list row 수: {len(valid_seq_list)}")

# 2. df_filtered3에서 Seq가 위의 Seq 목록에 포함되는 row만 필터링
matched_rows = df_filtered3[df_filtered3['Seq'].isin(valid_seq_list)]

# 3. 개수 출력
print(f"조건에 해당하는 df_filtered3 row 수: {len(matched_rows)}")

조건에 해당하는 valid_seq_list row 수: 3477
조건에 해당하는 df_filtered3 row 수: 5801

In [19]:
df111_filtered = df111[df111['TagList'].apply(lambda x: not(pd.isna(x) or str(x).strip() == ''))]
df111_filtered.to_csv('master_info_eda.csv', index=False, encoding='utf-8-sig')

In [21]:
df111_filtered33 = df_filtered3[df_filtered3['Seq'].isin(valid_seq_list)]
df111_filtered33.to_csv('text_image_combined_eda.csv', index=False, encoding='utf-8-sig')

In [23]:
import pandas as pd

# 분석할 파일 목록
file_paths = {
    "master_info.csv": "master_info.csv",
    "text_image_combined": "text_image_combined.csv",
    "master_info_eda.csv": "master_info_eda.csv",
    "text_image_combined_eda": "text_image_combined_eda.csv"
}

# 파일별 구조 및 개수 출력
for name, path in file_paths.items():
    try:
        df = pd.read_csv(path)
        print(f"\n📁 파일: {path}")
        print(f"✅ 행(Row) 수: {len(df)}")
        print(f"✅ 열(Column) 수: {len(df.columns)}")
        print(f"📌 컬럼 목록: {list(df.columns)}")
        print("-" * 50)
    except FileNotFoundError:
        print(f"\n❌ 파일 '{path}'을 찾을 수 없습니다.")

📁 파일: master_info.csv
✅ 행(Row) 수: 11971
✅ 열(Column) 수: 12
📌 컬럼 목록: ['Seq', 'Title', 'ShopName', 'Address', 'Area (평형)', 'Cost', 'Style', 'Space', 'Apt Name', 'View Count', 'Editor', 'TagList']
--------------------------------------------------

📁 파일: text_image_combined.csv
✅ 행(Row) 수: 231697
✅ 열(Column) 수: 3
📌 컬럼 목록: ['Seq', '텍스트', '이미지']
--------------------------------------------------

📁 파일: master_info_eda.csv
✅ 행(Row) 수: 3477
✅ 열(Column) 수: 6
📌 컬럼 목록: ['Seq', 'Title', 'TagList', 'apply_space', 'apply_cost', 'apply_style']
--------------------------------------------------

📁 파일: text_image_combined_eda.csv
✅ 행(Row) 수: 5801
✅ 열(Column) 수: 3
📌 컬럼 목록: ['Seq', '텍스트', '이미지']
--------------------------------------------------

## AWS에 이미지 업로드
### kk2 파일에

In [ ]:
import boto3
import requests
from urllib.parse import urlparse
import os
from dotenv import load_dotenv

load_dotenv()

# AWS 인증 정보
aws_access_key_id = os.getenv("AWS_ACCESS_KEY_ID")
aws_secret_access_key = os.getenv("AWS_SECRET_ACCESS_KEY")
bucket_name = os.getenv("AWS_S3_BUCKET")
region_name = os.getenv("AWS_REGION")

# S3 클라이언트 생성
s3 = boto3.client(
    's3',
    aws_access_key_id=aws_access_key_id,
    aws_secret_access_key=aws_secret_access_key,
    region_name=region_name
)

# 이미지 URL 리스트
image_urls = [
    "https://example.com/image1.jpg",
    "https://example.com/image2.png",
    # ...
]

for url in image_urls:
    try:
        response = requests.get(url)
        response.raise_for_status()  # 오류 확인
        parsed_url = urlparse(url)
        file_name = os.path.basename(parsed_url.path)

        # S3에 업로드
        s3.put_object(
            Bucket=bucket_name,
            Key=f"built_case_image/{file_name}",
            Body=response.content,
            ContentType=response.headers.get('Content-Type', 'image/jpeg')
        )
        print(f"Uploaded {file_name} to S3.")
    except Exception as e:
        print(f"Failed to upload {url}: {e}")